version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      
      - run:
          name: Update Bundler
          command: gem install bundler
          
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      
      - run:
          name: Run rspec 
          command: bundle exec rspec 
