version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      
      - run:
          name: Which bundler?
          command: bundle -v
      
      - run:
          name: Update Bundler
          command: gem install bundler

      - run:
          name: Bundle Install
          command: bundle check || bundle install
      
      - run:
          name: apt-get install nodejs
          command: sudo apt-get install nodejs
      - run:
          name: Test loading index page 
          command: bundle exec rspec spec/controllers/core_controller_spec.rb:5
